<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706083619 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE invoice_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issuer_nif VARCHAR(20) NOT NULL, full_number VARCHAR(41) NOT NULL, issue_date VARCHAR(10) NOT NULL, invoice_type VARCHAR(4) NOT NULL, vat_total NUMERIC(12, 2) NOT NULL, total NUMERIC(12, 2) NOT NULL, generated_at VARCHAR(25) NOT NULL, previous_hash VARCHAR(64) DEFAULT NULL, hash VARCHAR(64) NOT NULL, invoice_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_200202C22989F1FD ON invoice_record (invoice_id)');
        $this->addSql('CREATE INDEX IDX_200202C2A76ED395 ON invoice_record (user_id)');
        $this->addSql('ALTER TABLE invoice_record ADD CONSTRAINT FK_200202C22989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice_record ADD CONSTRAINT FK_200202C2A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_user ADD tax_id VARCHAR(20) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE invoice_record DROP CONSTRAINT FK_200202C22989F1FD');
        $this->addSql('ALTER TABLE invoice_record DROP CONSTRAINT FK_200202C2A76ED395');
        $this->addSql('DROP TABLE invoice_record');
        $this->addSql('ALTER TABLE app_user DROP tax_id');
    }
}
