<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Work orders (partes de trabajo) + their material/service lines. New tables only — no change to existing
 * data, so the invoice hash chain is untouched.
 * ES: Partes de trabajo + sus líneas de material/servicio. Solo tablas nuevas — no toca datos existentes,
 * así que la cadena de hash de facturas queda intacta.
 */
final class Version20260711101940 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create work_order + work_order_line tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE work_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(12) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, labor_hours NUMERIC(6, 2) NOT NULL, labor_rate NUMERIC(12, 2) NOT NULL, labor_vat_rate NUMERIC(5, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, customer_id INT NOT NULL, converted_invoice_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DDD2E8B7A76ED395 ON work_order (user_id)');
        $this->addSql('CREATE INDEX IDX_DDD2E8B79395C3F3 ON work_order (customer_id)');
        $this->addSql('CREATE INDEX IDX_DDD2E8B79DC100AB ON work_order (converted_invoice_id)');
        $this->addSql('CREATE TABLE work_order_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, vat_rate NUMERIC(5, 2) NOT NULL, work_order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_87862332582AE764 ON work_order_line (work_order_id)');
        $this->addSql('ALTER TABLE work_order ADD CONSTRAINT FK_DDD2E8B7A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE work_order ADD CONSTRAINT FK_DDD2E8B79395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE work_order ADD CONSTRAINT FK_DDD2E8B79DC100AB FOREIGN KEY (converted_invoice_id) REFERENCES invoice (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE work_order_line ADD CONSTRAINT FK_87862332582AE764 FOREIGN KEY (work_order_id) REFERENCES work_order (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE work_order DROP CONSTRAINT FK_DDD2E8B7A76ED395');
        $this->addSql('ALTER TABLE work_order DROP CONSTRAINT FK_DDD2E8B79395C3F3');
        $this->addSql('ALTER TABLE work_order DROP CONSTRAINT FK_DDD2E8B79DC100AB');
        $this->addSql('ALTER TABLE work_order_line DROP CONSTRAINT FK_87862332582AE764');
        $this->addSql('DROP TABLE work_order');
        $this->addSql('DROP TABLE work_order_line');
    }
}
