<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708084943 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE certificate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, issued_at DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, installation_type VARCHAR(12) NOT NULL, use_type VARCHAR(30) DEFAULT NULL, address VARCHAR(255) NOT NULL, locality VARCHAR(120) DEFAULT NULL, province VARCHAR(80) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, titular_name VARCHAR(150) NOT NULL, titular_nif VARCHAR(20) DEFAULT NULL, titular_address VARCHAR(255) DEFAULT NULL, company_name VARCHAR(150) NOT NULL, company_reg_number VARCHAR(40) DEFAULT NULL, company_nif VARCHAR(20) DEFAULT NULL, installer_name VARCHAR(150) DEFAULT NULL, installer_license VARCHAR(40) DEFAULT NULL, max_power NUMERIC(8, 3) DEFAULT NULL, installed_power NUMERIC(8, 3) DEFAULT NULL, voltage INT DEFAULT NULL, supply_type VARCHAR(12) DEFAULT NULL, earthing_scheme VARCHAR(8) DEFAULT NULL, circuits INT DEFAULT NULL, derivation_section VARCHAR(40) DEFAULT NULL, iga_current VARCHAR(20) DEFAULT NULL, differential_sensitivity VARCHAR(20) DEFAULT NULL, earth_resistance VARCHAR(20) DEFAULT NULL, earth_conductor_section VARCHAR(20) DEFAULT NULL, observations TEXT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_219CDA4AA76ED395 ON certificate (user_id)');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4AA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE certificate DROP CONSTRAINT FK_219CDA4AA76ED395');
        $this->addSql('DROP TABLE certificate');
    }
}
